module.exports = {
    ashb :  'Ashby (Berkeley)' ,
    antc :  'Antioch' ,
    conc :  'Concord' ,
    rock :  'Rockridge' ,
    lafy :  'Lafayette' ,
    orin :  'Orinda' ,
    pitt :  'Pittsburg/Bay Point' ,
    pctr :  'Pittsburg Center' ,
    phil :  'Pleasant Hill' ,
    rich :  'Richmond' ,
    dbrk :  'Downtown Berkeley' ,
    dubl :  'Dublin/Pleasanton' ,
    deln :  'El Cerrito del Norte' ,
    plza :  'El Cerrito Plaza' ,
    hayw :  'Hayward' ,
    frmt :  'Fremont' ,
    shay :  'South Hayward',
    nbrk :  'North Berkeley' ,
    ncon :  'North Concord/Martinez' ,
    wcrk :  'Walnut Creek' ,
    wdub :  'West Dublin' ,
    ucty :  'Union City' 
};        